/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class Buffer
 *
 * This file has been generated by dub 2.2.1.
 */
#include "dub/dub.h"
#include "media/Buffer.h"

using namespace media;

/** media::Buffer::Buffer()
 * include/media/Buffer.h:53
 */
static int Buffer_Buffer(lua_State *L) {
  try {
    Buffer *retval__ = new Buffer();
    dub::pushudata(L, retval__, "media.Buffer", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}

/** virtual media::Buffer::~Buffer()
 * include/media/Buffer.h:62
 */
static int Buffer__Buffer(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "media.Buffer"));
    if (userdata->gc) {
      Buffer *self = (Buffer *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize media::Buffer::frameData(lua_State *L)
 * include/media/Buffer.h:68
 */
static int Buffer_frameData(lua_State *L) {
  try {
    Buffer *self = *((Buffer **)dub::checksdata(L, 1, "media.Buffer"));
    return self->frameData(L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "frameData: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "frameData: Unknown exception");
  }
  return dub::error(L);
}

/** size_t media::Buffer::frameSize()
 * include/media/Buffer.h:76
 */
static int Buffer_frameSize(lua_State *L) {
  try {
    Buffer *self = *((Buffer **)dub::checksdata(L, 1, "media.Buffer"));
    lua_pushnumber(L, self->frameSize());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "frameSize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "frameSize: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize media::Buffer::frameInfo(lua_State *L)
 * include/media/Buffer.h:80
 */
static int Buffer_frameInfo(lua_State *L) {
  try {
    Buffer *self = *((Buffer **)dub::checksdata(L, 1, "media.Buffer"));
    return self->frameInfo(L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "frameInfo: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "frameInfo: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int Buffer___tostring(lua_State *L) {
  Buffer *self = *((Buffer **)dub::checksdata_n(L, 1, "media.Buffer"));
  lua_pushfstring(L, "media.Buffer: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg Buffer_member_methods[] = {
  { "new"          , Buffer_Buffer        },
  { "__gc"         , Buffer__Buffer       },
  { "frameData"    , Buffer_frameData     },
  { "frameSize"    , Buffer_frameSize     },
  { "frameInfo"    , Buffer_frameInfo     },
  { "__tostring"   , Buffer___tostring    },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_media_Buffer(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "media.Buffer");
  // <mt>

  // register member methods
  dub::fregister(L, Buffer_member_methods);
  // setup meta-table
  dub::setup(L, "media.Buffer");
  // <mt>
  return 1;
}
