/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class Camera
 *
 * This file has been generated by dub 2.2.1.
 */
#include "dub/dub.h"
#include "media/Camera.h"

using namespace media;

/** Cast (class_name)
 * 
 */
static int Camera__cast_(lua_State *L) {

  Camera *self = *((Camera **)dub::checksdata_n(L, 1, "media.Camera"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  int key_h = dub::hash(key, 2);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "media.Buffer")) break;
      *retval__ = static_cast<Buffer *>(self);
      return 1;
    }
  }
  return 0;
}

/** media::Camera::Camera(const char *device_uid=NULL)
 * include/media/Camera.h:46
 */
static int Camera_Camera(lua_State *L) {
  try {
    int top__ = lua_gettop(L);
    if (top__ >= 1) {
      const char *device_uid = dub::checkstring(L, 1);
      Camera *retval__ = new Camera(device_uid);
      retval__->dub_pushobject(L, retval__, "media.Camera", true);
      return 1;
    } else {
      Camera *retval__ = new Camera();
      retval__->dub_pushobject(L, retval__, "media.Camera", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}

/** virtual media::Camera::~Camera()
 * include/media/Camera.h:48
 */
static int Camera__Camera(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "media.Camera"));
    if (userdata->gc) {
      Camera *self = (Camera *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** double media::Camera::frameRate()
 * include/media/Camera.h:53
 */
static int Camera_frameRate(lua_State *L) {
  try {
    Camera *self = *((Camera **)dub::checksdata(L, 1, "media.Camera"));
    lua_pushnumber(L, self->frameRate());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "frameRate: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "frameRate: Unknown exception");
  }
  return dub::error(L);
}

/** void media::Camera::start()
 * include/media/Camera.h:60
 */
static int Camera_start(lua_State *L) {
  try {
    Camera *self = *((Camera **)dub::checksdata(L, 1, "media.Camera"));
    self->start();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "start: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "start: Unknown exception");
  }
  return dub::error(L);
}

/** void media::Camera::stop()
 * include/media/Camera.h:64
 */
static int Camera_stop(lua_State *L) {
  try {
    Camera *self = *((Camera **)dub::checksdata(L, 1, "media.Camera"));
    self->stop();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "stop: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "stop: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize media::Camera::__tostring(lua_State *L)
 * include/media/Camera.h:73
 */
static int Camera___tostring(lua_State *L) {
  try {
    Camera *self = *((Camera **)dub::checksdata(L, 1, "media.Camera"));
    return self->__tostring(L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "__tostring: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__tostring: Unknown exception");
  }
  return dub::error(L);
}

/** static LuaStackSize media::Camera::sources(lua_State *L)
 * include/media/Camera.h:69
 */
static int Camera_sources(lua_State *L) {
  try {
    return Camera::sources(L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "sources: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "sources: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize media::Buffer::frameData(lua_State *L)
 * include/media/Buffer.h:68
 */
static int Camera_frameData(lua_State *L) {
  try {
    Camera *self = *((Camera **)dub::checksdata(L, 1, "media.Camera"));
    return self->frameData(L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "frameData: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "frameData: Unknown exception");
  }
  return dub::error(L);
}

/** size_t media::Buffer::frameSize()
 * include/media/Buffer.h:76
 */
static int Camera_frameSize(lua_State *L) {
  try {
    Camera *self = *((Camera **)dub::checksdata(L, 1, "media.Camera"));
    lua_pushnumber(L, self->frameSize());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "frameSize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "frameSize: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize media::Buffer::frameInfo(lua_State *L)
 * include/media/Buffer.h:80
 */
static int Camera_frameInfo(lua_State *L) {
  try {
    Camera *self = *((Camera **)dub::checksdata(L, 1, "media.Camera"));
    return self->frameInfo(L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "frameInfo: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "frameInfo: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== METHODS

static const struct luaL_Reg Camera_member_methods[] = {
  { "_cast_"       , Camera__cast_        },
  { "new"          , Camera_Camera        },
  { "__gc"         , Camera__Camera       },
  { "frameRate"    , Camera_frameRate     },
  { "start"        , Camera_start         },
  { "stop"         , Camera_stop          },
  { "__tostring"   , Camera___tostring    },
  { "sources"      , Camera_sources       },
  { "frameData"    , Camera_frameData     },
  { "frameSize"    , Camera_frameSize     },
  { "frameInfo"    , Camera_frameInfo     },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_media_Camera(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "media.Camera");
  // <mt>

  // register member methods
  dub::fregister(L, Camera_member_methods);
  // setup meta-table
  dub::setup(L, "media.Camera");
  // <mt>
  return 1;
}
